### ISSUE TITLE
Downloaded Files Don't Come with Type

### ISSUE THREAD

**Issue by electroqobra** [JosephusPaye/blackboard-downloader#2]
I tried using your tool on my Blackboard page and got all of the files. Unfortunately the file type is not provided so it just says "file" when I look at it. I have to look back at my Blackboard in order to see what it was.  Is there a way for the script to detect and assign the type (docx or PDF for example)?

![Capture](https://user-images.githubusercontent.com/36612417/88084966-29122300-cb53-11ea-9206-5ae149e479c2.PNG)

**Comment by JosephusPaye** [comment]
Yeah sometimes the file listing in Blackboard has no extension. It's usually PDF though. You can rename the file to add `.pdf` extension.
